'$schema' = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$fill\
$status\
$cmd_duration\
$time\
$line_break\
"""

aws.disabled = true
gcloud.disabled = true

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
format = '[ $path ]($style)'
truncation_symbol = '... '

[fill]
symbol = " "

[git_branch]
symbol = ''
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[ $all_status$ahead_behind ]($style)'

[nodejs]
symbol = ''
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ''
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ''
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ''
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
format = '[ $time ]($style)'
