gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#c4b28a"
      - "bold"
    inactiveBorderColor:
      - "#625e5a"
    searchingActiveBorderColor:
      - "#938AA9"
      - "bold"
    optionsTextColor:
      - "#8ea49e"
    selectedLineBgColor:
      - "#2A2A37"
    cherryPickedCommitFgColor:
      - "#393836"
    cherryPickedCommitBgColor:
      - "#c4746e"
    markedBaseCommitFgColor:
      - "#393836"
    markedBaseCommitBgColor:
      - "#c4b28a"
    unstagedChangesColor:
      - "#c4b28a"
    defaultFgColor:
      - "#DCD7BA"

