# scrollback size
set -g history-limit 10000

################################
# Keybinds
###############################

# Changing ctrl b to ctrl a as the command button
unbind C-b
set -g prefix C-a

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1

# pass through xterm keys
set -g xterm-keys on

# Keep your finger on ctrl, or don't, same result
bind-key C-d detach-client
bind-key C-p paste-buffer

# Redraw the client (if interrupted by wall, etc)
bind R refresh-client

# reload tmux config with ctrl + a + r
unbind r
bind r source-file ~/.tmux.conf \; display 'Reloaded tmux config.'

# Vertical splits with \ or C-\
unbind '\'
unbind 'C-\'
bind-key '\' split-window -h
bind-key 'C-\' split-window -h

# Horizontal splits with v or C-h
unbind '-'
unbind 'C--'
bind-key '-' split-window
bind-key 'C--' split-window

# Using the mouse to switch panes
set -g mouse on

# Ctrl - t or t new window
unbind t
unbind C-t
bind-key t new-window
bind-key C-t new-window

# Ctrl - w or w to kill panes
unbind w
unbind C-w
bind-key w kill-pane
bind-key C-w kill-pane

# C + control q to kill session
unbind q
unbind C-q
bind-key q kill-session
bind-key C-q kill-session

unbind h
unbind C-h
bind-key h clear-history
bind-key C-h clear-history

# status bar theme
set -g status 'on'
set -g status-justify 'centre'
set -g status-left '#[fg=#ebcb8b] ▲ '
set -g status-interval 5
set -g status-right '#[fg=#d8dee9,bg=terminal]#(LC_TIME=ja_JP date "+%%m-%%d %%a %%H:%%M") '
set -g status-bg 'terminal'
set -g status-fg '#2E3440'
setw -g window-status-format '#[fg=#434c5e,bg=terminal]#I: #W '
setw -g window-status-current-format '#[fg=#d8dee9,bg=terminal]#I: #W '

# pane border color
set -g pane-active-border-style fg=#4C566A
